packages:
  - packages/*
  - apps/*
  # @generated begin forker-workspaces
  - forks/ccc/packages/*
  - "!forks/ccc/packages/demo"
  - "!forks/ccc/packages/docs"
  - "!forks/ccc/packages/examples"
  - "!forks/ccc/packages/faucet"
  - "!forks/ccc/packages/playground"
  - "!forks/ccc/packages/tests"
  # @generated end forker-workspaces

catalog:
  "@ckb-ccc/core": ^1.12.2
  "@types/node": ^24.8.1

minimumReleaseAge: 1440
minimumReleaseAgeByPackage:
