packages:
  - packages/*
  - apps/*
  # @generated begin fork-workspaces
  - ccc-fork/ccc/packages/*
  - "!ccc-fork/ccc/packages/demo"
  - "!ccc-fork/ccc/packages/docs"
  - "!ccc-fork/ccc/packages/examples"
  - "!ccc-fork/ccc/packages/faucet"
  - "!ccc-fork/ccc/packages/playground"
  - "!ccc-fork/ccc/packages/tests"
  # @generated end fork-workspaces

catalog:
  "@ckb-ccc/core": ^1.12.2
  "@types/node": ^24.8.1

minimumReleaseAge: 1440
minimumReleaseAgeByPackage:
