packages:
  - packages/*
  - apps/*
  - ccc/.cache/packages/*
  - '!ccc/.cache/packages/demo'
  - '!ccc/.cache/packages/docs'
  - '!ccc/.cache/packages/examples'
  - '!ccc/.cache/packages/faucet'
  - '!ccc/.cache/packages/playground'
  - '!ccc/.cache/packages/tests'

catalog:
  '@ckb-ccc/core': ^1.12.2
  '@types/node': ^24.8.1

minimumReleaseAge: 1440
